
{% set data = load_setup_py_data() %}


package:
    name    : cdbclerk

    version : {{ data.get('version') }}


source:
    path: ..

build:
    number: 1
    noarch: python

requirements:
    build:
      - python >=3.11
      - setuptools

    run:
      - python >=3.11

test:
    imports:
      - cdbclerk

    requires:
      - pytest

about:
  home: https://github.com/spc-group/cdbclerk
  license: All rights reserved
  summary: A tool for updating CA/PVA PVs from the components database.
